name: "Code Format Workflow"

on:
  workflow_call:
    inputs:
      push-code:
        description: Commit the files after changes has been made.
        type: boolean
        default: true
      terraform-version:
        description: Terraform version to install
        type: string
        default : "1.5.2"
      python-version:
        description: Python version to install
        type: string
        default: "3.9.17"

jobs:
  format:
    runs-on: [ubuntu-latest]
    environment: all-automation
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v5

      - name: "Checkout All Repos Tooling Private"
        uses: actions/checkout@v5
        with:
          repository: nicolas-furtadods-org/all-repos-tooling-private
          token: ${{ secrets.GITHUB_TOKEN }}
          path: tooling/

      - name: "Install Terraform"
        uses:  hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
            
      - name: "Install Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Install Python Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tooling/scripts/requirements.txt
          pip install black autopep8 isort
            
      - name: Terraform Format Recursive
        run: | 
          terraform fmt -recursive .
    
      - name: Python Format
        run: |
          black .
          autopep8 --recursive --in-place --aggressive .
          isort .

      - name: Set git user
        if: inputs.push-code
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit modified files
        if: inputs.push-code
        run: |
          git add --all -- ':!tooling/'
          git commit -m "Terraform and Python Code Format"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # Necessary if case the code is good and nothing has changed

      #- name: Generate GitHub App Token
      #  if: inputs.push-code
      #  id: generate_token     
      #  env:
      #    GH_APPLICATION_ID: ${{ secrets.GH_APPLICATION_ID }}
      #    GH_APPLICATION_INSTALLATION_ID: ${{ secrets.GH_APPLICATION_INSTALLATION_ID }}
      #    GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      #  run: python ./tooling/scripts/generate_token.py
      
      - name: Push code
        if: inputs.push-code
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.github_app_token }}
        run: |
          git push
        
            